CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Auth0Id" text NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Goals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Type" integer NOT NULL,
    "TargetValue" numeric NOT NULL,
    "Unit" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "TargetDate" timestamp with time zone NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "CompletedDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Goals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Goals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WorkoutPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WorkoutPlans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkoutPlans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Exercises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "WorkoutPlanId" integer NOT NULL,
    "Sets" integer NOT NULL,
    "Reps" integer NOT NULL,
    "Weight" numeric,
    "Duration" interval,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Exercises_WorkoutPlans_WorkoutPlanId" FOREIGN KEY ("WorkoutPlanId") REFERENCES "WorkoutPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WorkoutLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "WorkoutPlanId" integer,
    "Notes" text NOT NULL,
    "WorkoutDate" timestamp with time zone NOT NULL,
    "Duration" interval NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WorkoutLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkoutLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkoutLogs_WorkoutPlans_WorkoutPlanId" FOREIGN KEY ("WorkoutPlanId") REFERENCES "WorkoutPlans" ("Id")
);

CREATE TABLE "ExerciseLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkoutLogId" integer NOT NULL,
    "ExerciseId" integer,
    "ExerciseName" text NOT NULL,
    "Sets" integer NOT NULL,
    "Reps" integer NOT NULL,
    "Weight" numeric,
    "Duration" interval,
    "Notes" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExerciseLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExerciseLogs_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id"),
    CONSTRAINT "FK_ExerciseLogs_WorkoutLogs_WorkoutLogId" FOREIGN KEY ("WorkoutLogId") REFERENCES "WorkoutLogs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ExerciseLogs_ExerciseId" ON "ExerciseLogs" ("ExerciseId");

CREATE INDEX "IX_ExerciseLogs_WorkoutLogId" ON "ExerciseLogs" ("WorkoutLogId");

CREATE INDEX "IX_Exercises_WorkoutPlanId" ON "Exercises" ("WorkoutPlanId");

CREATE INDEX "IX_Goals_UserId" ON "Goals" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Auth0Id" ON "Users" ("Auth0Id");

CREATE INDEX "IX_WorkoutLogs_UserId" ON "WorkoutLogs" ("UserId");

CREATE INDEX "IX_WorkoutLogs_WorkoutPlanId" ON "WorkoutLogs" ("WorkoutPlanId");

CREATE INDEX "IX_WorkoutPlans_UserId" ON "WorkoutPlans" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250318201010_InitialPostgresMigration', '9.0.3');

COMMIT;

